name: Resonate
favicon: null
layout_spectrum: 0.0269
typography_spectrum: 0.81
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#998675'
    - '#808040'
    - '#8e7171'
    - '#aa8080'
    - '#808060'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: null
    url: null
